/*
 * This file is generated by jOOQ.
 */
package com.example.messenger.jooqData;


import org.jooq.impl.CatalogImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = -133376746;

    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    private DefaultCatalog() {
        super("");
    }
}
