/*
 * This file is generated by jOOQ.
 */
package com.example.messenger.jooqData;


import org.jooq.Catalog;
import org.jooq.impl.SchemaImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1377489412;

    public static final Public PUBLIC = new Public();

    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }
}
