spring:
  datasource:
    driver-class-name: @datasource.driver@
    url: @datasource.url@
    username: @datasource.login@
    password: @datasource.password@
  jooq:
    sql-dialect: Postgres
  liquibase:
    change-log: classpath:liquibase/db.changlog-master.xml