/*
 * This file is generated by jOOQ.
 */
package com.example.messenger.jooqData.tables;


import com.example.messenger.jooqData.Public;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleTags extends TableImpl<Record> {

    private static final long serialVersionUID = 1030903243;

    public static final ArticleTags ARTICLE_TAGS = new ArticleTags();

    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    public final TableField<Record, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('article_tags_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    public final TableField<Record, Integer> TAG_ID = createField("tag_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    public final TableField<Record, Integer> ARTICLE_ID = createField("article_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    public ArticleTags() {
        this(DSL.name("article_tags"), null);
    }

    public ArticleTags(String alias) {
        this(DSL.name(alias), ARTICLE_TAGS);
    }

    public ArticleTags(Name alias) {
        this(alias, ARTICLE_TAGS);
    }

    private ArticleTags(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private ArticleTags(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<Record, Integer> getIdentity() {
        return Internal.createIdentity(com.example.messenger.jooqData.tables.ArticleTags.ARTICLE_TAGS, com.example.messenger.jooqData.tables.ArticleTags.ARTICLE_TAGS.ID);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(com.example.messenger.jooqData.tables.ArticleTags.ARTICLE_TAGS, "article_tags_pkey", com.example.messenger.jooqData.tables.ArticleTags.ARTICLE_TAGS.ID);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(
              Internal.createUniqueKey(com.example.messenger.jooqData.tables.ArticleTags.ARTICLE_TAGS, "article_tags_pkey", com.example.messenger.jooqData.tables.ArticleTags.ARTICLE_TAGS.ID)
        );
    }

    @Override
    public ArticleTags as(String alias) {
        return new ArticleTags(DSL.name(alias), this);
    }

    @Override
    public ArticleTags as(Name alias) {
        return new ArticleTags(alias, this);
    }

    @Override
    public ArticleTags rename(String name) {
        return new ArticleTags(DSL.name(name), null);
    }

    @Override
    public ArticleTags rename(Name name) {
        return new ArticleTags(name, null);
    }
}
