/*
 * This file is generated by jOOQ.
 */
package com.example.messenger.jooqData.tables;


import com.example.messenger.jooqData.Public;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ArticleImages extends TableImpl<Record> {

    private static final long serialVersionUID = -1157602607;

    public static final ArticleImages ARTICLE_IMAGES = new ArticleImages();

    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    public final TableField<Record, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('article_images_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    public final TableField<Record, Integer> ARTICLE_ID = createField("article_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    public final TableField<Record, String> IMAGE_POSITION_ID = createField("image_position_id", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    public final TableField<Record, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    public ArticleImages() {
        this(DSL.name("article_images"), null);
    }

    public ArticleImages(String alias) {
        this(DSL.name(alias), ARTICLE_IMAGES);
    }

    public ArticleImages(Name alias) {
        this(alias, ARTICLE_IMAGES);
    }

    private ArticleImages(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private ArticleImages(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<Record, Integer> getIdentity() {
        return Internal.createIdentity(com.example.messenger.jooqData.tables.ArticleImages.ARTICLE_IMAGES, com.example.messenger.jooqData.tables.ArticleImages.ARTICLE_IMAGES.ID);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(com.example.messenger.jooqData.tables.ArticleImages.ARTICLE_IMAGES, "article_images_pkey", com.example.messenger.jooqData.tables.ArticleImages.ARTICLE_IMAGES.ID);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(
              Internal.createUniqueKey(com.example.messenger.jooqData.tables.ArticleImages.ARTICLE_IMAGES, "article_images_pkey", com.example.messenger.jooqData.tables.ArticleImages.ARTICLE_IMAGES.ID)
        );
    }

    @Override
    public ArticleImages as(String alias) {
        return new ArticleImages(DSL.name(alias), this);
    }

    @Override
    public ArticleImages as(Name alias) {
        return new ArticleImages(alias, this);
    }

    @Override
    public ArticleImages rename(String name) {
        return new ArticleImages(DSL.name(name), null);
    }

    @Override
    public ArticleImages rename(Name name) {
        return new ArticleImages(name, null);
    }
}
