/*
 * This file is generated by jOOQ.
 */
package com.example.messenger.jooqData.tables;


import com.example.messenger.jooqData.Public;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Article extends TableImpl<Record> {

    private static final long serialVersionUID = -2004057713;

    public static final Article ARTICLE = new Article();

    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    public final TableField<Record, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('article_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    public final TableField<Record, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('article_user_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    public final TableField<Record, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    public final TableField<Record, String> TOPIC = createField("topic", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    public final TableField<Record, String> MAIN_TEXT = createField("main_text", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    public final TableField<Record, LocalDateTime> CREATION_DATE = createField("creation_date", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    public Article() {
        this(DSL.name("article"), null);
    }

    public Article(String alias) {
        this(DSL.name(alias), ARTICLE);
    }

    public Article(Name alias) {
        this(alias, ARTICLE);
    }

    private Article(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private Article(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<Record, Integer> getIdentity() {
        return Internal.createIdentity(com.example.messenger.jooqData.tables.Article.ARTICLE, com.example.messenger.jooqData.tables.Article.ARTICLE.ID);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(com.example.messenger.jooqData.tables.Article.ARTICLE, "article_pkey", com.example.messenger.jooqData.tables.Article.ARTICLE.ID);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(
              Internal.createUniqueKey(com.example.messenger.jooqData.tables.Article.ARTICLE, "article_pkey", com.example.messenger.jooqData.tables.Article.ARTICLE.ID)
        );
    }

    @Override
    public Article as(String alias) {
        return new Article(DSL.name(alias), this);
    }

    @Override
    public Article as(Name alias) {
        return new Article(alias, this);
    }

    @Override
    public Article rename(String name) {
        return new Article(DSL.name(name), null);
    }

    @Override
    public Article rename(Name name) {
        return new Article(name, null);
    }
}
