/*
 * This file is generated by jOOQ.
 */
package com.example.messenger.jooqData.tables;


import com.example.messenger.jooqData.Public;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;


@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRoles extends TableImpl<Record> {

    private static final long serialVersionUID = -1314354756;

    public static final UserRoles USER_ROLES = new UserRoles();

    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    public final TableField<Record, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('user_roles_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    public final TableField<Record, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('user_roles_user_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    public final TableField<Record, String> ROLE = createField("role", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    public UserRoles() {
        this(DSL.name("user_roles"), null);
    }

    public UserRoles(String alias) {
        this(DSL.name(alias), USER_ROLES);
    }

    public UserRoles(Name alias) {
        this(alias, USER_ROLES);
    }

    private UserRoles(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private UserRoles(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<Record, Integer> getIdentity() {
        return Internal.createIdentity(com.example.messenger.jooqData.tables.UserRoles.USER_ROLES, com.example.messenger.jooqData.tables.UserRoles.USER_ROLES.ID);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Internal.createUniqueKey(com.example.messenger.jooqData.tables.UserRoles.USER_ROLES, "user_roles_pkey", com.example.messenger.jooqData.tables.UserRoles.USER_ROLES.ID);
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(
              Internal.createUniqueKey(com.example.messenger.jooqData.tables.UserRoles.USER_ROLES, "user_roles_pkey", com.example.messenger.jooqData.tables.UserRoles.USER_ROLES.ID)
        );
    }

    @Override
    public UserRoles as(String alias) {
        return new UserRoles(DSL.name(alias), this);
    }

    @Override
    public UserRoles as(Name alias) {
        return new UserRoles(alias, this);
    }

    @Override
    public UserRoles rename(String name) {
        return new UserRoles(DSL.name(name), null);
    }

    @Override
    public UserRoles rename(Name name) {
        return new UserRoles(name, null);
    }
}
